@echo off
chcp 65001 >nul
title Installing Transcription System...
echo Downloading installer...
powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/shidurei-ui/transcription-system/main/installer_gui.ps1' -OutFile '%TEMP%\installer_gui.ps1' -UseBasicParsing; & '%TEMP%\installer_gui.ps1'"
